### ISSUE TITLE
Docker secrets

### ISSUE THREAD

**Issue by robflate** [svenihoney/docker-wetty-alpine#10]
Is it possible to use docker secrets for the env variables?

https://docs.docker.com/engine/swarm/secrets/

When I try something like;

```
ssh_username:
  file: $SECRETSDIR/ssh_username
```

```
environment:
  REMOTE_SSH_USER: /run/secrets/ssh_username
secrets:
  - ssh_username
```

the `REMOTE_SSH_USER` var is a string `/run/secrets/ssh_username` rather than the contents of the file.

Thanks.

**Comment by svenihoney** [comment]
The image does not support reading secrets from docker secrets (meaning reading from files). Perhaps a solution like in https://medium.com/lucjuggery/from-env-variables-to-docker-secrets-bc8802cacdfd may work to supply the environment variable values from secrets to the container.
