### ISSUE TITLE
2FA with Wetty

### ISSUE THREAD

**Issue by cgott82** [svenihoney/docker-wetty-alpine#12]
After installing the 2FA "libpam-google-authenticator", it is not possible for me to register via Wetty.

Error: password is no longer recognized.

**Comment by svenihoney** [comment]
Is this a problem with wetty or a problem with the docker container only? This is the repo for the docker container only...

Are you able to login with plain ssh?

**Comment by cgott82** [comment]
ich kann mich von meinen Clients ganz normal über ssh einloggen, nur wenn ich die seite wetty.123.xyz (ReverseProxy eingestellt) aufrufe, kann ich den Nutzer eingeben (selbe wie Console) nur Passwort wird nicht erkannt. 
Wetty läuft bei mir im Container, lief bis dato auch fehlerfrei.

**Comment by svenihoney** [comment]
Please stick to English, so this may help others to solve similar problems also.

Did you try to run wetty directly as stated here: https://github.com/butlerx/wetty#usage ? If you have the same problem, please report the issue there since it is no docker container problem then...
