### ISSUE TITLE
defining BASE breaks the app

### ISSUE THREAD

**Issue by VietTralala** [svenihoney/docker-wetty-alpine#14]
Hi, 
first off thanks for the minimalistic and very transparent Dockerfile. I managed to run wetty locally without defining the env-variable `BASE`. Thus I could reach wetty via `localhost:3000`. 

However I want to make wetty reachable under `localhost:3000/terminal`. Thus I defined `BASE='terminal'`. However this broke the app. 

__Fix__
One needs to define the base with slashes: `BASE='/terminal/'`. This isnt mentioned anywhere. Maybe one can add some line to run.sh or the docs to fix this?

**Comment by svenihoney** [comment]
It would be better to have an example like this in the docs for wetty itself, since it has nothing to do with the docker container. Please edit and create a pull request againt https://github.com/butlerx/wetty/blob/main/docs/flags.md.
