### ISSUE TITLE
dockerized version do not work, Always show Cannot GET /

### ISSUE THREAD

**Issue by raulfg3** [svenihoney/docker-wetty-alpine#2]
Hello I use lates dockerized version from https://hub.docker.com/r/svenihoney/wetty
until this version wetty works fine and as expected.

from this version alvays show: Cannt Get /.

For a working dokerized version I always need to define SSHOST and SSHPORT because I need to SSH to my main PC, not SSH inside the docker (127.0.0.1 is inside the docker and is not what users wants).

PD:Becuase you delete old docker image, is not possible for me or for users to donwload prior image that really works.
![3](https://user-images.githubusercontent.com/12611785/55803175-1ef12000-5ada-11e9-82c8-6fc6addda76b.jpg)
![2](https://user-images.githubusercontent.com/12611785/55803176-1ef12000-5ada-11e9-8801-85e80f6eac44.jpg)

**Comment by svenihoney** [comment]
Hello raulfg3,
please read the documentation. The default path wetty is accessed is /wetty. So accessing your wetty instance will be done by http://your.host/wetty/. You can configure this to be the root path by adding `-e BASE=/` to your docker command.
The environment variables to use can be seen in wetty's index file: https://github.com/krishnasrinivas/wetty/blob/master/index.js. You can simply pass then with docker's -e options as you like. Have a look at the `docker-compose.yml` file as an example for this.
