### ISSUE TITLE
Error opening browser page

### ISSUE THREAD

**Issue by geoffae** [svenihoney/docker-wetty-alpine#3]
Hi,
I use openmediavault, this has a plugin for installation and configuration of docker containers, the previous version of wetty worked with serverIP:3000 but the latest version returns Cannot GET /

It will work if I use serverIP:3000/wetty/ssh/root has something changed in the new in the new version?

**Comment by svenihoney** [comment]
Please have a look at #2. There is a description about the wetty standard behaviour and how you can adapt to the previous default behaviour.
