### ISSUE TITLE
run.sh: not found

### ISSUE THREAD

**Issue by BelphegorPrime** [svenihoney/docker-wetty-alpine#5]
When i start the Container I get the following error inside it´s logs:

/bin/sh: ./run.sh: not found

**Comment by svenihoney** [comment]
I can't reproduce this. Please give more details how you start the container to enable me to reproduce the issue.

**Comment by BelphegorPrime** [comment]
Hi, 

looks like the problem wasn´t with docerk-wetty-alpine.
I use portainer and ouroboros to update my running containers.
Portainer has a [bug](https://github.com/portainer/portainer/issues/3604) where the entrypoint of the updated container is not changed.

So I had do recreate the container manually and then it worked again.
