### ISSUE TITLE
Is there https support with --sslkey and --sslcert options?

### ISSUE THREAD

**Issue by michael-pellegrini** [svenihoney/docker-wetty-alpine#8]
Is there support for passing `--sslkey` and `--sslcert` options to container for https access?
I'm bind mounting the key.pem and cert.pem into the container and trying to pass them to wetty with this command. 
`docker run -dt -v /home/user1/.ssh/wetty:/home/node/.ssh -e REMOTE_SSH_SERVER=10.10.10.10 -e REMOTE_SSH_PORT=22 -e REMOTE_SSH_USER=user1 -e SSLKEY=/home/node/.ssh/key.pem -e SSLCERT=/home/node.ssh/cert.pem -p 4000:3000 --name term1  svenihoney/wetty`

However, curl produces this error. `OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 10.10.10.10:3000`

From: [https://github.com/butlerx/wetty/blob/master/docs/https.md](url)

To run WeTTy directly with SSL use both the --sslkey and --sslcert flags and pass them the path too your cert and key as follows:
wetty --sslkey key.pem --sslcert cert.pem

**Comment by svenihoney** [comment]
No, currently not. Feel free to create a PR for this. But since my recommendation is running this behind a proxy, I would recommend to use the HTTPS capabilities of the proxy, e.g. by https://github.com/nginx-proxy/nginx-proxy#ssl-support.
